# This file was generated by GoReleaser. DO NOT EDIT.
cask "licenseware-collector" do
  name "licenseware-collector"
  desc "Licenseware Collector Agent."
  homepage "https://licenseware-collector.com"
  version "0.10.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "licenseware-collector"

  on_macos do
    url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_darwin_all.tar.gz"
    sha256 "4a4337ebb1dadc00769feb8ee9da421e416d0216cd8bf073ece5654f8d7747ac"
  end

  on_linux do
    on_intel do
      url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_linux_amd64.tar.gz"
      sha256 "b91394e5b45e134b1b7c6e0be06cc515d14705f94459e73e2def73960fafb539"
    end
    on_arm do
      url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_linux_arm64.tar.gz"
      sha256 "fd5ff227ed8d26405c4b1f8aef9744709dd4e2d28dc1b996b0c8414323e63ad8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/licenseware-collector"]
    end
  end

  # No zap stanza required
end
