# This file was generated by GoReleaser. DO NOT EDIT.
cask "licenseware-collector" do
  version "0.10.2"

  on_macos do
    url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_darwin_all.tar.gz"
    sha256 "57d4aea3a311d2a1bde77f2ede440eaf77d5071bfdcc3ca31fecebce1be49c04"
  end

  on_linux do
    on_intel do
      url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_linux_amd64.tar.gz"
      sha256 "c76d39df9afb6d4a704b96c62dc6ac47b2057223f0692d430d852dd7669116c5"
    end
    on_arm do
      url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_linux_arm64.tar.gz"
      sha256 "d26328904b9b5e748264c451664e4192345b366812b1af4d41cf160a27b3da43"
    end
  end

  name "licenseware-collector"
  desc "Licenseware Collector Agent."
  homepage "https://licenseware-collector.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "licenseware-collector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/licenseware-collector"]
    end
  end

  # No zap stanza required

end
