# This file was generated by GoReleaser. DO NOT EDIT.
cask "licenseware-collector" do
  name "licenseware-collector"
  desc "Licenseware Collector Agent."
  homepage "https://licenseware-collector.com"
  version "0.9.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "licenseware-collector"

  on_macos do
    url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_darwin_all.tar.gz"
    sha256 "dc27392db897a64a31634414a9dcbb968d8a8f745bfb6ea97847495f2923a36c"
  end

  on_linux do
    on_intel do
      url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_linux_amd64.tar.gz"
      sha256 "18dedb64a59d9afb267dfc917cb5e5a8e6a76b1468d804059212a1afadcb20b6"
    end
    on_arm do
      url "https://github.com/licenseware/collector/releases/download/v#{version}/collector_linux_arm64.tar.gz"
      sha256 "b2c81749e123749ee11c376c1abd5af135da0261fa5ea1bdb450983937eada7b"
    end
  end

  # No zap stanza required
end
