# This file was generated by GoReleaser. DO NOT EDIT.
cask "ojdm-collector" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "3d300a9cae039771e4be99f4effcaadc386d13f9d3eeb8c9d46e513d7f94f2d6"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e1c4a2c1e435f92f5d7d803e99ca337e50b36c133af647124de95a7749c9530"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d98a0a193af853d25bcb4bfbf1b287a1ec4646c2364573a0b2da185602c812e7"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab25c3d9a0c0f1ffe36db0ae69f12ba98d34a2746ab18b9c030982ec7d2fc2a8"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_linux_arm64.tar.gz"
    end
  end

  name "ojdm-collector"
  desc "Licenseware OJDM Collector - gather all Java/JDK info in one place."
  homepage "https://licenseware.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ojdm-collector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ojdm-collector"]
    end
  end

  # No zap stanza required

end
