# This file was generated by GoReleaser. DO NOT EDIT.
cask "ojdm-collector" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "fa6340a3d335a94854a274246301e6b99f2b87f30bfac323e4006de4a460b4b2"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78fecfed923d96148e5b875687d349adaaddecb6c143c540cd72909b78dcd277"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cbf664f05d92852cf549cf75149ab0bfc80bc76d1a9418439b7b5c869c1b9a51"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b4d71e4f3b72f99b4815e1c4151acbc44f745fc50a1db137da40487df662057"
      url "https://github.com/licenseware/ojdm-collector/releases/download/v#{version}/ojdm-collector_linux_arm64.tar.gz"
    end
  end

  name "ojdm-collector"
  desc "Licenseware OJDM Collector - gather all Java/JDK info in one place."
  homepage "https://licenseware.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ojdm-collector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ojdm-collector"]
    end
  end

  # No zap stanza required

end
