# This file was generated by GoReleaser. DO NOT EDIT.
cask "ory-admin-ui" do
  name "ory-admin-ui"
  desc "The admin user interface for Ory services"
  homepage "https://github.com/licenseware/ory-admin-ui"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ory-admin-ui"

  on_macos do
    on_intel do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_darwin_amd64.tar.gz"
      sha256 "7ba2d04b3688090443eae9d48fe17704a9062cbc3b860172bb6ff2bff359de88"
    end
    on_arm do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_darwin_arm64.tar.gz"
      sha256 "dd2b03b81b4b650e3062c6f9d7c3ef82c04d0f12075c467ed9529556942a8328"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_linux_amd64.tar.gz"
      sha256 "eeb57f1a8e5d154123c25aeff1c14ad450524fc8585492dabe687c2687eeed3a"
    end
    on_arm do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_linux_arm64.tar.gz"
      sha256 "3f5fbca289263609d51ac326009283fa55aba145b5004f4f81408e98f76f82c2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ory-admin-ui"]
    end
    puts "✨ ory-admin-ui installed successfully!"
    puts ""
    puts "📝 Tip: You can enable shell completion by running:"
    puts "   ory-admin-ui completion bash  # for bash"
    puts "   ory-admin-ui completion zsh   # for zsh"
    puts "   ory-admin-ui completion fish  # for fish"
    puts ""
    puts "📚 For more information and usage instructions, visit:"
    puts "   https://github.com/licenseware/ory-admin-ui"
  end

  # No zap stanza required
end
