# This file was generated by GoReleaser. DO NOT EDIT.
cask "ory-admin-ui" do
  name "ory-admin-ui"
  desc "The admin user interface for Ory services"
  homepage "https://github.com/licenseware/ory-admin-ui"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ory-admin-ui"

  on_macos do
    on_intel do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_darwin_amd64.tar.gz"
      sha256 "2aefe1d97bca79ae8057ccf28844b487c71c166adcf1ae9bd8e7aac31904026d"
    end
    on_arm do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_darwin_arm64.tar.gz"
      sha256 "4d27fee5a599068f7fbcf98207167296cd29dfa26b476f63de2eff5ac0a0fa82"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_linux_amd64.tar.gz"
      sha256 "95bc1eff0cbe31b04d949801ec7ac315a84a0041e0987a7942138bde1277ebf9"
    end
    on_arm do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_linux_arm64.tar.gz"
      sha256 "28c7684f1df968a6b311b2500870e033787d853b877458657bc66ce1f67426b6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ory-admin-ui"]
    end
    puts "✨ ory-admin-ui installed successfully!"
    puts ""
    puts "📝 Tip: You can enable shell completion by running:"
    puts "   ory-admin-ui completion bash  # for bash"
    puts "   ory-admin-ui completion zsh   # for zsh"
    puts "   ory-admin-ui completion fish  # for fish"
    puts ""
    puts "📚 For more information and usage instructions, visit:"
    puts "   https://github.com/licenseware/ory-admin-ui"
  end

  # No zap stanza required
end
