# This file was generated by GoReleaser. DO NOT EDIT.
cask "ory-admin-ui" do
  name "ory-admin-ui"
  desc "The admin user interface for Ory services"
  homepage "https://github.com/licenseware/ory-admin-ui"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ory-admin-ui"

  on_macos do
    on_intel do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_darwin_amd64.tar.gz"
      sha256 "6cf2c293bd59d5f74aada2d52bc91906c71b069dd8079019f1de1f9a974f30f2"
    end
    on_arm do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_darwin_arm64.tar.gz"
      sha256 "980662f0c92cc5acd7f590456a7a7fafffe6edd9e4cffae0179db56c6bfc320c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_linux_amd64.tar.gz"
      sha256 "73aabaaf2ac578d329151cec85540d6aac2e9f0f98715fe839ec629fa68bffe7"
    end
    on_arm do
      url "https://github.com/licenseware/ory-admin-ui/releases/download/v#{version}/ory-admin-ui_linux_arm64.tar.gz"
      sha256 "8328d7b4a07af82b4d5ccae2a608794c5e97c82a3dd0e527487d9fe0747c8fa2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ory-admin-ui"]
    end
    puts "✨ ory-admin-ui installed successfully!"
    puts ""
    puts "📝 Tip: You can enable shell completion by running:"
    puts "   ory-admin-ui completion bash  # for bash"
    puts "   ory-admin-ui completion zsh   # for zsh"
    puts "   ory-admin-ui completion fish  # for fish"
    puts ""
    puts "📚 For more information and usage instructions, visit:"
    puts "   https://github.com/licenseware/ory-admin-ui"
  end

  # No zap stanza required
end
